#!/usr/bin/env bash
set -Eeuo pipefail

thisDir="$(dirname "$(readlink -f "$BASH_SOURCE")")"
source "$thisDir/.constants.sh" \
	'<target-dir> <command> [args...]' \
	'rootfs apt-get update'

eval "$dgetopt"
while true; do
	flag="$1"; shift
	dgetopt-case "$flag"
	case "$flag" in
		--) break ;;
		*) eusage "unknown flag '$flag'" ;;
	esac
done

targetDir="${1:-}"; shift || eusage 'missing target-dir'
cmd="${1:-}"; shift || eusage 'missing command'
[ -n "$targetDir" ]
epoch="$(< "$targetDir/debuerreotype-epoch")"
[ -n "$epoch" ]

export targetDir epoch

[ -n "$targetDir" ] # just to be safe

cp /etc/resolv.conf "$targetDir"/etc/resolv.conf
cp /etc/apt/apt.conf.d/99-dbdbdp-proxy.conf "$targetDir"/etc/apt/apt.conf.d/

chroot "$targetDir" /usr/bin/env -i PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" TZ="$TZ" LC_ALL="$LC_ALL" SOURCE_DATE_EPOCH="$epoch" "$cmd" "$@"

rm "$targetDir"/etc/apt/apt.conf.d/99-dbdbdp-proxy.conf
rm "$targetDir"/etc/resolv.conf
touch "$targetDir"/etc/resolv.conf
epoch="$(date --date "2020-01-01T00:00:00Z" +%s)"
touch --no-dereference --date="@$epoch" "$targetDir"/etc/resolv.conf
