#!/usr/bin/env bash
set -o errexit -o errtrace -o functrace -o nounset -o pipefail

targetDir="$1"
cmd="$2"
shift
shift

# XXX replace this thing
epoch="$(< "$targetDir/debuerreotype-epoch")"

# Carry forward resolv.conf and hosts
mv "$targetDir"/etc/resolv.conf "$targetDir"/etc/resolv.conf_

cp /etc/resolv.conf "$targetDir"/etc/resolv.conf
cp /etc/hosts "$targetDir"/etc/hosts

>&2 echo "-------------------------------"
>&2 echo "Dubo chroot"
>&2 echo "-------------------------------"
>&2 echo "Target: $targetDir"
>&2 echo "Cmd: $cmd $*"
>&2 echo "-------------------------------"

# Chroot, with the additional environment
chroot "$targetDir" /usr/bin/env -i \
  DEBIAN_FRONTEND="$DEBIAN_FRONTEND" \
  TERM="$TERM" \
  LANG="$LANG" \
  LC_ALL="$LC_ALL" \
  TZ="$TZ" \
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
  "$cmd" "$@"

rm -f "$targetDir"/etc/resolv.conf
rm -f "$targetDir"/etc/hosts

mv "$targetDir"/etc/resolv.conf_ "$targetDir"/etc/resolv.conf

touch --no-dereference --date="@$epoch" "$targetDir"/etc/resolv.conf
