#!/usr/bin/env bash
set -o errexit -o errtrace -o functrace -o nounset -o pipefail

# Get all arguments
args=("$@")

# Optionally honor random options (see https://linux.die.net/man/5/apt.conf)
# Examples:
# - proxy: "Acquire::HTTP::proxy=http://proxy:1234/"
# - ignore signature expiracy (typical with snapshot): "Acquire::Check-Valid-Until=no"
# - user-agent: "Acquire::HTTP::User-Agent=DuboDubonDuponey/0.1"
APT_OPTIONS=${APT_OPTIONS:-}
for i in ${APT_OPTIONS[*]}; do
  args+=("-o" "$i")
done

# Optionally override source list
if [ "$APT_SOURCES" ]; then
  printf "%s\n" "$APT_SOURCES" > /tmp/sources.list
  args+=("-o" "Dir::Etc::SourceList=/tmp/sources.list")
fi

# Optionally add additional trusteddb
if [ "$APT_TRUSTED" ]; then
  printf "%s" "$APT_TRUSTED" | base64 -d > /etc/apt/trusted.gpg.d/dbdbdp.gpg
fi

# Call the real apt-get now
/usr/bin/apt-get "${args[@]}"

rm -f /tmp/sources.list
rm -f /etc/apt/trusted.gpg.d/dbdbdp.gpg
