#!/usr/bin/env bash
set -o errexit -o errtrace -o functrace -o nounset -o pipefail

# Get all arguments
args=("$@")

# Optionally honor random options (see https://linux.die.net/man/5/apt.conf)
# Examples:
# - proxy: "Acquire::HTTP::proxy=http://proxy:1234/"
# - ignore signature expiracy (typical with snapshot): "Acquire::Check-Valid-Until=no"
# - user-agent: "Acquire::HTTP::User-Agent=DuboDubonDuponey/0.1"
APT_OPTIONS="${APT_OPTIONS:-}"
if [ "$APT_OPTIONS" ]; then
  for i in ${APT_OPTIONS[*]}; do
    args+=("-o" "$i")
  done
fi

# Optionally override source list
if [ "${APT_SOURCES:-}" ]; then
  printf "%s\n" "$APT_SOURCES" > /tmp/sources.list
  args+=("-o" "Dir::Etc::SourceList=/tmp/sources.list")
fi

# Optionally add additional trusteddb
if [ "${APT_GPG_KEYRING:-}" ]; then
  printf "%s" "$APT_GPG_KEYRING" | base64 -d > /etc/apt/trusted.gpg.d/dbdbdp.gpg
fi

# Optionally trust a CA (or cert chain)
if [ "${APT_TLS_CA:-}" ]; then
  printf "%s" "$APT_TLS_CA" | base64 -d > /tmp/ca.pem
  args+=("-o" "Acquire::https::CAInfo=/tmp/ca.pem")
fi

# Optionally add machine login info
if [ "${APT_NETRC:-}" ]; then
  printf "%s" "$APT_NETRC" | base64 -d > /tmp/auth.conf
  args+=("-o" "Dir::Etc::netrc=/tmp/auth.conf")
fi

# Call the real apt-get now
# >&2 printf "Running deviation: apt-get %s\n" "${args[*]}"
/usr/bin/apt-get "${args[@]}"

# Remove deviation list, ca, auth file, and gpg keyring
rm -f /tmp/sources.list
rm -f /tmp/ca.pem
rm -f /tmp/auth.conf
rm -f /etc/apt/trusted.gpg.d/dbdbdp.gpg
