#!/usr/bin/env bash
set -Eeuo pipefail

thisDir="$(dirname "$(readlink -f "$BASH_SOURCE")")"
source "$thisDir/.constants.sh" \
	'<target-dir> <command> [args...]' \
	'rootfs apt-get update'

eval "$dgetopt"
while true; do
	flag="$1"; shift
	dgetopt-case "$flag"
	case "$flag" in
		--) break ;;
		*) eusage "unknown flag '$flag'" ;;
	esac
done

targetDir="${1:-}"
shift
cmd="${1:-}"
shift
epoch="$(< "$targetDir/debuerreotype-epoch")"

export targetDir epoch

cp /etc/resolv.conf "$targetDir"/etc/resolv.conf

chroot "$targetDir" /usr/bin/env -i http_proxy="$APTPROXY" PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" TZ="$TZ" LC_ALL="$LC_ALL" SOURCE_DATE_EPOCH="$epoch" "$cmd" "$@"

rm "$targetDir"/etc/resolv.conf
touch "$targetDir"/etc/resolv.conf
touch --no-dereference --date="@$epoch" "$targetDir"/etc/resolv.conf

# cp /usr/local/sbin/apt-get "$targetDir"/usr/local/sbin/
# rm "$targetDir"/usr/local/sbin/apt-get
